version: '3.7'
services:

  app:
    image: addityar/nodejs-template:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
    healthcheck:
      test: curl -sS http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
